import { Lead, Profile, LeadNote, StatusHistory, DashboardMetrics, CallerPerformance, LeadIngestionLog, ManualDialLog, PatientCareJourney } from './types';


export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'user-admin-1',
    name: 'Agam Singh',
    email: 'agam@hommed.in',
    phone: '+919876543210',
    role: 'admin',
    is_active: true,
    created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'user-caller-1',
    name: 'Priya Sharma',
    email: 'priya@hommed.in',
    phone: '+919876543211',
    role: 'caller',
    is_active: true,
    created_at: new Date(Date.now() - 25 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'user-caller-2',
    name: 'Rahul Verma',
    email: 'rahul@hommed.in',
    phone: '+919876543212',
    role: 'caller',
    is_active: true,
    created_at: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'user-caller-3',
    name: 'Sneha Patel',
    email: 'sneha@hommed.in',
    phone: '+919876543213',
    role: 'caller',
    is_active: true,
    created_at: new Date(Date.now() - 15 * 24 * 3600 * 1000).toISOString(),
  },
];

const todayStr = new Date().toISOString().split('T')[0];
const yesterdayStr = new Date(Date.now() - 86400000).toISOString().split('T')[0];
const threeDaysAgoStr = new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-101',
    name: 'Vikram Malhotra',
    phone: '+919811223344',
    source: 'Facebook Lead Ads',
    campaign: 'Hommed Diagnostics Campaign - Delhi NCR',
    form_answers: {
      'Preferred Time': 'Morning 10 AM',
      'Health Service Requested': 'Full Body Health Checkup',
      'City': 'New Delhi',
    },
    status: 'qualified',
    assigned_to: 'user-caller-1',
    assigned_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    phone_attempt_count: 1,
    last_contacted_at: new Date(Date.now() - 86400000).toISOString(),
    next_follow_up_date: todayStr,
    next_follow_up_time: '10:30 AM',
    follow_up_stage: 1,
    is_cold: false,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'lead-102',
    name: 'Anita Roy',
    phone: '+919822334455',
    source: 'Facebook Lead Ads',
    campaign: 'Senior Care Consultation Campaign',
    form_answers: {
      'Service Required': 'Home Nursing Care',
      'Location': 'Gurugram',
    },
    status: 'phone_not_picked',
    assigned_to: 'user-caller-1',
    assigned_at: new Date(Date.now() - 86400000).toISOString(),
    phone_attempt_count: 2,
    last_contacted_at: yesterdayStr,
    next_follow_up_date: todayStr,
    next_follow_up_time: '02:15 PM',
    follow_up_stage: 0,
    is_cold: false,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: yesterdayStr,
  },
  {
    id: 'lead-103',
    name: 'Suresh Kumar',
    phone: '+919833445566',
    source: 'Facebook Lead Ads',
    campaign: 'Hommed Diagnostics Campaign - Delhi NCR',
    form_answers: {
      'Package': 'Diabetes Monitoring Care',
      'Pincode': '110017',
    },
    status: 'converted',
    order_status: 'rto',
    rto_reason: 'Customer refused delivery due to address mismatch',
    rto_flagged_at: new Date(Date.now() - 86400000).toISOString(),
    assigned_to: 'user-caller-2',
    assigned_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    phone_attempt_count: 3,
    last_contacted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    next_follow_up_date: null,
    next_follow_up_time: null,
    follow_up_stage: 4,
    is_cold: false,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'lead-104',
    name: 'Deepak Joshi',
    phone: '+919844556677',
    source: 'Facebook Lead Ads',
    campaign: 'Hommed Diagnostics Campaign - Noida',
    form_answers: {
      'Service': 'Thyroid & CBC Package',
    },
    status: 'unassigned',
    assigned_to: null,
    assigned_at: null,
    phone_attempt_count: 0,
    last_contacted_at: null,
    next_follow_up_date: null,
    next_follow_up_time: null,
    follow_up_stage: 0,
    is_cold: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lead-105',
    name: 'Kavita Menon',
    phone: '+919855667788',
    source: 'Facebook Lead Ads',
    campaign: 'Hommed Diagnostics Campaign - Noida',
    form_answers: {
      'Service': 'Physiotherapy Consultation',
    },
    status: 'unassigned',
    assigned_to: null,
    assigned_at: null,
    phone_attempt_count: 0,
    last_contacted_at: null,
    next_follow_up_date: null,
    next_follow_up_time: null,
    follow_up_stage: 0,
    is_cold: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lead-106',
    name: 'Rajesh Khanna',
    phone: '+919866778899',
    source: 'Facebook Lead Ads',
    campaign: 'General Wellness Campaign',
    form_answers: {
      'Query': 'Test Lead / Invalid Entry',
    },
    status: 'useless',
    useless_reason: 'spam',
    useless_note: 'Spam submission with fake digits',
    assigned_to: 'user-caller-3',
    assigned_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    phone_attempt_count: 1,
    last_contacted_at: threeDaysAgoStr,
    next_follow_up_date: null,
    next_follow_up_time: null,
    follow_up_stage: 0,
    is_cold: false,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: threeDaysAgoStr,
  },
  {
    id: 'lead-107',
    name: 'Meera Deshmukh',
    phone: '+919877889900',
    source: 'Facebook Lead Ads',
    campaign: 'Hommed Diagnostics Campaign - Delhi NCR',
    form_answers: {
      'Package': 'Full Body Care Package',
      'City': 'Faridabad',
    },
    status: 'converted',
    order_status: 'delivered',
    assigned_to: 'user-caller-3',
    assigned_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    phone_attempt_count: 2,
    last_contacted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    next_follow_up_date: null,
    next_follow_up_time: null,
    follow_up_stage: 3,
    is_cold: false,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
];

export const INITIAL_NOTES: LeadNote[] = [
  {
    id: 'note-1',
    lead_id: 'lead-101',
    author_id: 'user-caller-1',
    author_name: 'Priya Sharma',
    note: 'Called patient. Extremely interested in Full Body Checkup. Requested follow-up call tomorrow at 10:30 AM to finalize slot.',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'note-2',
    lead_id: 'lead-102',
    author_id: 'user-caller-1',
    author_name: 'Priya Sharma',
    note: 'First attempt: Phone rang out. Will attempt call again today at 02:15 PM.',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'note-3',
    lead_id: 'lead-103',
    author_id: 'user-caller-2',
    author_name: 'Rahul Verma',
    note: 'Order confirmed and shipped. Courier reported delivery failure due to wrong apartment number. Flagged RTO for address reconfirmation.',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const INITIAL_INGESTION_LOGS: LeadIngestionLog[] = [
  {
    id: 'ingest-1',
    meta_lead_id: 'leadgen_90112233',
    name: 'Vikram Malhotra',
    phone: '+919811223344',
    campaign: 'Hommed Diagnostics Campaign - Delhi NCR',
    status: 'success',
    created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'ingest-2',
    meta_lead_id: 'leadgen_90112234',
    name: 'Anita Roy',
    phone: '+919822334455',
    campaign: 'Senior Care Consultation Campaign',
    status: 'success',
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'ingest-3',
    meta_lead_id: 'leadgen_90112234',
    name: 'Anita Roy (Duplicate Test)',
    phone: '+919822334455',
    campaign: 'Senior Care Consultation Campaign',
    status: 'duplicate',
    error_detail: 'Lead with phone +919822334455 already exists in database',
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: 'ingest-4',
    meta_lead_id: 'leadgen_90112235',
    name: null,
    phone: null,
    campaign: 'Hommed Diagnostics Campaign',
    status: 'mapping_error',
    error_detail: 'Phone field missing or empty in Graph API payload',
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_MANUAL_DIAL_LOGS: ManualDialLog[] = [
  {
    id: 'dial-1',
    caller_id: 'user-caller-1',
    caller_name: 'Priya Sharma',
    phone: '+919899001122',
    notes: 'Ad-hoc call to walk-in inquiry',
    dialed_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_CARE_JOURNEYS: PatientCareJourney[] = [
  {
    id: 'journey-103',
    lead_id: 'lead-103',
    step1_status: 'sent',
    step1_sent_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    step2_diet_chart_url: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800',
    step2_status: 'sent',
    step2_scheduled_for: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
    step2_sent_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    step3_dispatch_status: 'sent',
    step3_dispatch_sent_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    step3_call_task_status: 'pending',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'journey-107',
    lead_id: 'lead-107',
    step1_status: 'sent',
    step1_sent_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    step2_diet_chart_url: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800',
    step2_status: 'sent',
    step2_scheduled_for: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
    step2_sent_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    step3_dispatch_status: 'sent',
    step3_dispatch_sent_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    step3_call_task_status: 'completed',
    step3_call_completed_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
];

